// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY4PlKOmFTHDCR5SJVp7WzzpUoFmwKrWA',
    appId: '1:194226769057:web:846fa1e4ff1bcbf50f74e0',
    messagingSenderId: '194226769057',
    projectId: 'todolistapp-123',
    authDomain: 'todolistapp-123-4207d.firebaseapp.com',
    storageBucket: 'todolistapp-123.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARQDuNqea_yg6Sk1YMuY8qJaV4ZBX1Psc',
    appId: '1:194226769057:android:0f8cd67c71f6540e0f74e0',
    messagingSenderId: '194226769057',
    projectId: 'todolistapp-123',
    storageBucket: 'todolistapp-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAShek0QrAlgpq14afYKMtmBpHQV2aGLcM',
    appId: '1:194226769057:ios:c4e713522175609a0f74e0',
    messagingSenderId: '194226769057',
    projectId: 'todolistapp-123',
    storageBucket: 'todolistapp-123.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAShek0QrAlgpq14afYKMtmBpHQV2aGLcM',
    appId: '1:194226769057:ios:c4e713522175609a0f74e0',
    messagingSenderId: '194226769057',
    projectId: 'todolistapp-123',
    storageBucket: 'todolistapp-123.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY4PlKOmFTHDCR5SJVp7WzzpUoFmwKrWA',
    appId: '1:194226769057:web:45ffd732ef963ea40f74e0',
    messagingSenderId: '194226769057',
    projectId: 'todolistapp-123',
    authDomain: 'todolistapp-123-4207d.firebaseapp.com',
    storageBucket: 'todolistapp-123.firebasestorage.app',
  );
}
